apiVersion: batch/v1
kind: Job
metadata:
  namespace: cdp  # namespace where the pvc's exist
  name: volume-migration
spec:
  completions: 1
  parallelism: 1
  backoffLimit: 3
  template:
    metadata:
      name: volume-migration
      labels:
        name: volume-migration
    spec:
      restartPolicy: Never
      containers:
        - name: volume-migration
          image: http://docker-private.infra.cloudera.com/cloudera_thirdparty/cldr-kubectl
          tty: true
          command: [ "/bin/sh" ]
          args: [ "-c", "cp -r -v /mnt/old/. /mnt/new" ]
          volumeMounts:
            - name: old-vol
              mountPath: /mnt/old
            - name: new-vol
              mountPath: /mnt/new
      volumes:
        - name: old-vol
          persistentVolumeClaim:
            claimName: pvc-ea369219-77b2-4bc6-8381-fa4a28f147c0 # change to data source pvc
        - name: new-vol
          persistentVolumeClaim:
            claimName: pvc-ea369219-77b2-4bc6-8381-fa4a28f147c0 # change to data target pvc
